name: Build Dev Image and Run Tests & Linters

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'project/app/**'
      - 'project/tests/**'
      - 'project/migrations/**'
      - 'project/scripts/entrypoint.sh'
      - 'project/pyproject.toml'
      - 'project/pdm.lock'
      - 'project/docker/dev.Dockerfile'
      - '.github/workflows/dev.yml'
      
env:
  MODE: dev
  IMAGE: ghcr.io/${{ github.repository }}/dev-image

jobs:
  build-test-lint:
    name: Build Docker Image and Run Tests & Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v4

      - name: Log in to gitHub container registry
        id: login-ghcr
        run: echo "${GH_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Pull existing docker image
        id: pull-existing-docker-image
        run: |
          docker pull ${{ env.IMAGE }}:latest || true

      - name: Build docker image
        id: build-docker-image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE }}:latest \
            --tag ${{ env.IMAGE }}:latest \
            --file ./project/docker/${{ env.MODE }}.Dockerfile \
            ./project

      - name: Push docker image to github container registry
        id: push-docker-image
        run: |
          docker push ${{ env.IMAGE }}:latest

      - name: Run docker container
        id: run-docker-container
        run: |
          docker run \
            --name test-container \
            --detach \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e DATABASE_URL="${DB_URL}" \
            -e DATABASE_TEST_URL="${DB_URL}" \
            -p 5003:8765 \
            ${{ env.IMAGE }}:latest
        env:
          DB_URL: sqlite://test.db

      - name: Run tests
        id: run-tests
        run: |
          docker exec test-container python -m pytest . 
      
      - name: Run black
        id: run-black
        run: |
          docker exec test-container black . --check 
        
      - name: Run isort
        id: run-isort
        run: |
          docker exec test-container isort . --check-only
